theme: jekyll-theme-minimal
ignore_theme_config: true
lsi: true
safe: true
source: index.md
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
